### ISSUE TITLE
Question: How do you use the #replace tokens# during local development

### ISSUE THREAD

**Issue by UniperMaster** [toolboc/IoTEdge-DevOps#10]
Question

you have used the replace token in the module.json file to set the ACR host and the build number. how can I replace this tokens during local debug development or deployment as they are not environment vars. 

The deployment.template.json is easy enough as I can create an alternative file but as for the module.json can this be replaced with an alternative config file used by the deployment template

**Comment by toolboc** [comment]
@UniperMaster, it is possible to replace values locally by creating a .env file to store key / value pairs and appending `$` to variable entries within the deployment template and module.json files (as opposed to wrapping with `#{` / `}#` which is the default delimiter used by the [Replace Tokens task](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens&WT.mc_id=iot-0000-pdecarlo)).  The VS Code tooling will use the values from the .env file to replace any matching variables during local build.  An example of this in action can be gleaned from the following [.env file](https://github.com/microsoft/vision-ai-developer-kit/blob/master/samples/official/camera-tagging/.env), [module.json](https://github.com/microsoft/vision-ai-developer-kit/blob/master/samples/official/camera-tagging/modules/CameraTaggingModule/module.json), and associated [deployment.template.json](https://github.com/microsoft/vision-ai-developer-kit/blob/master/samples/official/camera-tagging/deployment.template.json).

It may be possible to make this work in local builds and Azure DevOps by using a [variable configuration in Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch&WT.mc_id=iot-0000-pdecarlo) (without a checked in .env) and an .env file locally with a properly delimited deployment.template.json (using `$` for variables of interest), then building with the "IoT Edge - Build Modules task" in Azure DevOps or within VS Code using the local IoT Edge Dev tooling (effectively removing any reliance on the Replace Tokens Task).  When this project was initially created, this was not possible as the ability to replace values in the deployment template using environment variables was not present in the IoT Edge tooling.  Let me know if you find that this works for you, if you can do it using a single deployment template for both builds (Azure DevOps & local) then it might be worth updating the documentation to use this technique.

**Comment by UniperMaster** [comment]
Thank you for your reply , this worked fine with ReplaceTokens using the following 
        tokenPrefix: '$'
        tokenSuffix: ''

Also have to make all .env var UPPERCASE as a mix seemed to not be recognized

i.e CONTAINER_REGISTRY_HOST 

"repository": "$CONTAINER_REGISTRY_HOST/samplemodule",

also had to set build.buildId as a variable in the pipeline as the env would except the '.' in the var name
