### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by darthkurak** [toolboc/IoTEdge-DevOps#3]
Hi. This may be not related to this repo, but as you are in the topic, i will try to ask :)
I tried to use Azure Devops Iot Edge task to build my modules for arm-32 platform.
I have python module and it seems to fail on that Task. I'm getting such an error: 

```
Step 3/10 : RUN apt-get update &&     apt-get install -y --no-install-recommends libboost-python1.62.0 python3-pip libpython3-dev &&     rm -rf /var/lib/apt/lists/*

 ---> Running in ad6ca2ff6b91

standard_init_linux.go:207: exec user process caused "exec format error"

ERROR: The command '/bin/sh -c apt-get update &&     apt-get install -y --no-install-recommends libboost-python1.62.0 python3-pip libpython3-dev &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1
```
I checked iotedgedev build command locally inside docker container with the same files mounted as volume and it succeed build all modules.
Did you have chance to manage similar problem?

**Comment by toolboc** [comment]
It sounds like you might need to set the default platform to “arm32v7” in the build task to ensure that you are building for your host architecture (ARM32).  “exec format error” is usually in response to attempting to run an incompatible binary on an unsupported host architecture.

![FC83FC74-EEA3-4D81-A6AF-E75D8DA6DF01](https://user-images.githubusercontent.com/2018336/60379498-7fb53800-99f9-11e9-9ef0-cfa446def821.jpeg)
