### ISSUE TITLE
update connectionstatus in smoke test

### ISSUE THREAD

**Issue by shizn** [toolboc/IoTEdge-DevOps#5]
Always disconnected during smoke test:
![image](https://user-images.githubusercontent.com/3619378/84120384-581f7a00-aa68-11ea-84fc-39db21f1d451.png)

Per https://github.com/Azure/iotedge/issues/2733, the current recommendation to get connectionstatus for 1.0.9 runtime is to use the [ping direct method](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-edgeagent-direct-method#ping).
Our updated sample edgeSmokeTest.sh is here - https://github.com/Azure-Samples/azure-iot-edge-devops-sample-dotnet/commit/87953df3d56ec5c51f2ff2c7962d700df3ff3cb7#diff-540e66f7c97d49837a36c35bb5f5c4b4

Please help update the script. Thanks!!

**Comment by toolboc** [comment]
@shizn, thank you for the notification.  The issue has been resolved by updating edgeSmokeTest.sh in a0d7443

![image](https://user-images.githubusercontent.com/2018336/84150515-93e61f80-aa27-11ea-9b0a-f004a14ff24c.png)
