### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by wmpauli** [toolboc/IoTEdge-DevOps#6]
Hi, 

The following link in step 1 appears to be dead: https://marketplace.visualstudio.com/items?itemName=qetza.replacetoken&wt.mc_id=iotedgedevops-github-pdecarlo

**Comment by toolboc** [comment]
Fixed in https://github.com/toolboc/IoTEdge-DevOps/commit/5ce1cd4e71cc009c7361322176c407e452a0d303, thank you for reporting the issue!
